### ISSUE TITLE
How to connect OLED display for the ESP8266 / D1 Mini?

### ISSUE THREAD

**Issue by vshowboy8** [AlexLynd/ESP8266-Wardriving#8]
How to connect the OLED display with d1 mini

**Comment by AlexLynd** [comment]
Hey!  You can look up the pinout for the ESP8266 / D1 Mini and see that pins `D2` and `D1` are used for I2C.  
So you have to wire `SDA` > `D2` and `SCL` > `D1`.   `SCL` is sometimes `SCK`.
